### ISSUE TITLE
Is this project support latest yolox??

### ISSUE THREAD

**Issue by zzzfo** [FeiGeChuanShu/ncnn-android-yolox#8]
I try to use latest yolox(version 0.1.0) in this project, I modified the corresponding parameters, when I run, the program force quit

**Comment by zzzfo** [comment]
I tested in ncnn, it can detect the object,but when i deployed it in your project,it can't detect,I was wondering if something wrong in you code......

**Comment by Peppachou** [comment]
> 我在ncnn中测试过，它可以检测到对象，但是当我将它部署到您的项目中时，它无法检测到，我想知道您的代码是否有问题......

你现在可以实现 训练自己的数据，在android上进行目标检测吗？

**Comment by FeiGeChuanShu** [comment]
> > 我在ncnn中测试过，它可以检测到对象，但是当我将它部署到您的项目中时，它无法检测到，我想知道您的代码是否有问题......
> 
> 你现在可以实现 训练自己的数据，在android上进行目标检测吗？
可以参考这个 https://github.com/FeiGeChuanShu/ncnn-yolox-hand，如果还有问题，如果方便可以把模型发我帮你测试一下

**Comment by FeiGeChuanShu** [comment]
> I tested in ncnn, it can detect the object,but when i deployed it in your project,it can't detect,I was wondering if something wrong in you code......

is there some error  debu info?  or reference this project
https://github.com/FeiGeChuanShu/ncnn-yolox-hand

**Comment by Peppachou** [comment]
你好 这两个工程我都看了，并且对比了。还是有一些问题，我将yolox训练的权重放到android的工程中，android程序可以运行，但是不显示检测框。模型是将训练好的权重文件.bin和.param文件发给你吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FeiGeChuanShu/ncnn-android-yolox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月28日(星期六) 晚上11:38
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [FeiGeChuanShu/ncnn-android-yolox] Is this project support latest yolox?? (#8)





   
我在ncnn中测试过，它可以检测到对象，但是当我将它部署到您的项目中时，它无法检测到，我想知道您的代码是否有问题......
  
你现在可以实现 训练自己的数据，在android上进行目标检测吗？
 可以参考这个 https://github.com/FeiGeChuanShu/ncnn-yolox-hand，
 如果还有问题，如果方便可以把模型发我帮你测试一下
  
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FeiGeChuanShu** [comment]
> 你好 这两个工程我都看了，并且对比了。还是有一些问题，我将yolox训练的权重放到android的工程中，android程序可以运行，但是不显示检测框。模型是将训练好的权重文件.bin和.param文件发给你吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "FeiGeChuanShu/ncnn-android-yolox" ***@***.***&gt;; 发送时间:&nbsp;2021年8月28日(星期六) 晚上11:38 ***@***.***&gt;; 抄送:&nbsp;" ***@***.******@***.***&gt;; 主题:&nbsp;Re: [FeiGeChuanShu/ncnn-android-yolox] Is this project support latest yolox?? (#8) 我在ncnn中测试过，它可以检测到对象，但是当我将它部署到您的项目中时，它无法检测到，我想知道您的代码是否有问题...... 你现在可以实现 训练自己的数据，在android上进行目标检测吗？ 可以参考这个 [https://github.com/FeiGeChuanShu/ncnn-yolox-hand，](https://github.com/FeiGeChuanShu/ncnn-yolox-hand%EF%BC%8C) 如果还有问题，如果方便可以把模型发我帮你测试一下 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

onnx模型即可

**Comment by Peppachou** [comment]
这是一个手部动作（七步洗手法）七分类的训练模型，谢谢你。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FeiGeChuanShu/ncnn-android-yolox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月28日(星期六) 晚上11:52
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [FeiGeChuanShu/ncnn-android-yolox] Is this project support latest yolox?? (#8)





  
你好 这两个工程我都看了，并且对比了。还是有一些问题，我将yolox训练的权重放到android的工程中，android程序可以运行，但是不显示检测框。模型是将训练好的权重文件.bin和.param文件发给你吗？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "FeiGeChuanShu/ncnn-android-yolox" @.&gt;; 发送时间:&nbsp;2021年8月28日(星期六) 晚上11:38 @.&gt;; 抄送:&nbsp;" @.@.&gt;; 主题:&nbsp;Re: [FeiGeChuanShu/ncnn-android-yolox] Is this project support latest yolox?? (#8) 我在ncnn中测试过，它可以检测到对象，但是当我将它部署到您的项目中时，它无法检测到，我想知道您的代码是否有问题...... 你现在可以实现 训练自己的数据，在android上进行目标检测吗？ 可以参考这个 https://github.com/FeiGeChuanShu/ncnn-yolox-hand， 如果还有问题，如果方便可以把模型发我帮你测试一下 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
onnx模型即可
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zzzfo** [comment]
> > 我在ncnn中测试过，它可以检测到对象，但是当我将它部署到您的项目中时，它无法检测到，我想知道您的代码是否有问题......
> 
> 你现在可以实现 训练自己的数据，在android上进行目标检测吗？



> 你好 这两个工程我都看了，并且对比了。还是有一些问题，我将yolox训练的权重放到android的工程中，android程序可以运行，但是不显示检测框。模型是将训练好的权重文件.bin和.param文件发给你吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "FeiGeChuanShu/ncnn-android-yolox" ***@***.***&gt;; 发送时间:&nbsp;2021年8月28日(星期六) 晚上11:38 ***@***.***&gt;; 抄送:&nbsp;" ***@***.******@***.***&gt;; 主题:&nbsp;Re: [FeiGeChuanShu/ncnn-android-yolox] Is this project support latest yolox?? (#8) 我在ncnn中测试过，它可以检测到对象，但是当我将它部署到您的项目中时，它无法检测到，我想知道您的代码是否有问题...... 你现在可以实现 训练自己的数据，在android上进行目标检测吗？ 可以参考这个 [https://github.com/FeiGeChuanShu/ncnn-yolox-hand，](https://github.com/FeiGeChuanShu/ncnn-yolox-hand%EF%BC%8C) 如果还有问题，如果方便可以把模型发我帮你测试一下 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我的情况和你一样

**Comment by zzzfo** [comment]
> > > 我在ncnn中测试过，它可以检测到对象，但是当我将它部署到您的项目中时，它无法检测到，我想知道您的代码是否有问题......
> > 
> > 
> > 你现在可以实现 训练自己的数据，在android上进行目标检测吗？
> > 可以参考这个 https://github.com/FeiGeChuanShu/ncnn-yolox-hand
> > 如果还有问题，如果方便可以把模型发我帮你测试一下

我还是不能实现，我怎么发送模型给您啊？这个直接上传不了。。。。。
程序可以正常运行，就是检测不出来物体。。

**Comment by FeiGeChuanShu** [comment]
> > > > 我在ncnn中测试过，它可以检测到对象，但是当我将它部署到您的项目中时，它无法检测到，我想知道您的代码是否有问题......
> > > 
> > > 
> > > 你现在可以实现 训练自己的数据，在android上进行目标检测吗？
> > > 可以参考这个 https://github.com/FeiGeChuanShu/ncnn-yolox-hand
> > > 如果还有问题，如果方便可以把模型发我帮你测试一下
> 
> 我还是不能实现，我怎么发送模型给您啊？这个直接上传不了。。。。。
> 程序可以正常运行，就是检测不出来物体。。

774074168@qq.com

**Comment by RTae** [comment]
I have same issue as you @zzzfo , I use the android example from official YOLOX repository. I can open the app but when I push inference button, it force quit from app. I test this code with legacy weight it's working file. After update 0.1.0 the app is crash. If you want to take a look my code here [link](https://github.com/RTae/YOLOX-android) @FeiGeChuanShu

**Comment by FeiGeChuanShu** [comment]
> I have same issue as you @zzzfo , I use the android example from official YOLOX repository. I can open the app but when I push inference button, it force quit from app. I test this code with legacy weight it's working file. After update 0.1.0 the app is crash. If you want to take a look my code here [link](https://github.com/RTae/YOLOX-android) @FeiGeChuanShu

![QQ截图20210830082839](https://user-images.githubusercontent.com/80833738/131270585-eec8a85f-58c0-4af7-87cc-8d6d2a458cf5.jpg)
change the input node index from 791 to 683

**Comment by zzzfo** [comment]
感谢作者大大  @FeiGeChuanShu ，修改https://github.com/FeiGeChuanShu/ncnn-android-yolox/blob/main/app/src/main/jni/yolox.cpp#L344
  ncnn::Mat in = ncnn::Mat::from_pixels_resize(rgb.data, ncnn::Mat::PIXEL_RGB2BGR, img_w, img_h, w, h);
注释掉L354即可

**Comment by RTae** [comment]
> > I have same issue as you @zzzfo , I use the android example from official YOLOX repository. I can open the app but when I push inference button, it force quit from app. I test this code with legacy weight it's working file. After update 0.1.0 the app is crash. If you want to take a look my code here [link](https://github.com/RTae/YOLOX-android) @FeiGeChuanShu
> 
> ![QQ截图20210830082839](https://user-images.githubusercontent.com/80833738/131270585-eec8a85f-58c0-4af7-87cc-8d6d2a458cf5.jpg)
> change the index from 791 to 683

Thank you @FeiGeChuanShu it's work. You save my day.

**Comment by gyin2010** [comment]
> 感谢作者大大 @FeiGeChuanShu ，修改https://github.com/FeiGeChuanShu/ncnn-android-yolox/blob/main/app/src/main/jni/yolox.cpp#L344
> ncnn::Mat in = ncnn::Mat::from_pixels_resize(rgb.data, ncnn::Mat::PIXEL_RGB2BGR, img_w, img_h, w, h);
> 注释掉L354即可


This save my ass!!! Thx aloooooot~

**Comment by hoanhvmetavi** [comment]
> 感谢作者大大 @FeiGeChuanShu ，修改https://github.com/FeiGeChuanShu/ncnn-android-yolox/blob/main/app/src/main/jni/yolox.cpp#L344
> ncnn::Mat in = ncnn::Mat::from_pixels_resize(rgb.data, ncnn::Mat::PIXEL_RGB2BGR, img_w, img_h, w, h);
> 注释掉L354即可
> 
Sorry but just comment this line (354) will make line 349 error.

`ncnn::copy_make_border(in, in_pad, 0, hpad, 0, wpad, ncnn::BORDER_CONSTANT, 114.f);
`
_**error: use of undeclared identifier 'in'**_

How can you run that? Please guide me.
